In [1]:
import math
import copy
import numpy as np
import pandas as pd
import random

import networkx as nx

In [2]:
#This is a list of toy problems that would be useful to solve

In [6]:
'''
Question #1. 

Given a string of length n, write a function that outputs all permutations of the string
#example, "abc" -> bca, cab, bac, etc
'''
    
def perm(a, l=0):
    
    if(l==len(a)):
        print (a, l)
    else:
        #This loop eventually passes over every index position in the list
        #l represents the number of layers of the tree descent
        #At the same time the process involves us fixing as many as one less 
        #then the total number of elements in the list, 
        #thus when descending we increment l, telling us that we are fixing the character 
        #at the lth index position with prior
        #positions already fixed at higher levels of the tree
        
        #The key trick is to realize this should be written as a for loop!
        for i in range(l, len(a)):
       
            a[l], a[i] = a[i], a[l]
       
            perm(a, l+1)
       
            a[l], a[i] = a[i], a[l] #This line rearranges the elements to what they were prior to the last perm call, 
       

In [10]:
perm(list('abcd'))

['a', 'b', 'c', 'd'] 4
['a', 'b', 'd', 'c'] 4
['a', 'c', 'b', 'd'] 4
['a', 'c', 'd', 'b'] 4
['a', 'd', 'c', 'b'] 4
['a', 'd', 'b', 'c'] 4
['b', 'a', 'c', 'd'] 4
['b', 'a', 'd', 'c'] 4
['b', 'c', 'a', 'd'] 4
['b', 'c', 'd', 'a'] 4
['b', 'd', 'c', 'a'] 4
['b', 'd', 'a', 'c'] 4
['c', 'b', 'a', 'd'] 4
['c', 'b', 'd', 'a'] 4
['c', 'a', 'b', 'd'] 4
['c', 'a', 'd', 'b'] 4
['c', 'd', 'a', 'b'] 4
['c', 'd', 'b', 'a'] 4
['d', 'b', 'c', 'a'] 4
['d', 'b', 'a', 'c'] 4
['d', 'c', 'b', 'a'] 4
['d', 'c', 'a', 'b'] 4
['d', 'a', 'c', 'b'] 4
['d', 'a', 'b', 'c'] 4


In [795]:
'''
Permutations of select length
'''
def permutations(iterable, r=None):
    # permutations('ABCD', 2) --> AB AC AD BA BC BD CA CB CD DA DB DC
    # permutations(range(3)) --> 012 021 102 120 201 210
    pool = tuple(iterable)
    n = len(pool)
    r = n if r is None else r
    if r > n:
        return
    indices = list(range(n))
    cycles = list(range(n, n-r, -1))
    yield tuple(pool[i] for i in indices[:r])
    while n:
        for i in reversed(range(r)):
            print (i, cycles[i])
            cycles[i] -= 1
            print (i, cycles[i])
            if cycles[i] == 0:
                indices[i:] = indices[i+1:] + indices[i:i+1]
                cycles[i] = n - i
            else:
                j = cycles[i]
                print (i, j, indices, indices[i], indices[-j])
                indices[i], indices[-j] = indices[-j], indices[i]
                print (i, j, indices[i], indices[-j])
                yield tuple(pool[i] for i in indices[:r])
                break
        else:
            return

In [789]:
'''
Permutations of select length
'''
def permutations(iterable, r=None):
    # permutations('ABCD', 2) --> AB AC AD BA BC BD CA CB CD DA DB DC
    # permutations(range(3)) --> 012 021 102 120 201 210
    pool = tuple(iterable)
    n = len(pool)
    r = n if r is None else r
    if r > n:
        return
    indices = list(range(n))
    cycles = list(range(n, n-r, -1))
    yield tuple(pool[i] for i in indices[:r])
    while n:
        for i in reversed(range(r)):
            print (i, list(reversed(range(r))))
            
            yield(i)
        else:
            return

In [790]:
q = permutations('abc', 2)

In [5]:
'''
Question 2. 

Find the square root of a number without using math functions
'''

In [594]:
#Doesn't always work, result is diverging
#Have to use correct formula
#Key to recognize using newton's method and apply it to root finding
#Can't cut by half, have to cut by the estimate!
def sqrtCutHalf(num, estimate, values, count=0):
  
    new_estimate = 0.5*(estimate+(num/estimate))
    print (new_estimate)
    #print (estimate, half_squared, diff_half, new_try)
    values.append(new_estimate)
    if count>10: 
        return values
    else:
        return sqrtCutHalf(num, new_estimate, values, count+1)

In [601]:
q = sqrtCutHalf(10, 8, [])

4.625
3.393581081081081
3.170160376279714
3.162287460494848
3.1622776601835656
3.162277660168379
3.162277660168379
3.162277660168379
3.162277660168379
3.162277660168379
3.162277660168379
3.162277660168379


In [8]:
'''
Question 3.
You are given a 2D array (representing a world map). Adjacent cells with the same number represents 
some nationality. Count the number of all nationalities. What is the right approach/algorithm here?
Question is ambigious, is this count how many nationalities there are or count the population of each nationality?
Do you know how many nationalities there are in total?
Take "easy" problem, the number of nationalities is known
assumption, diagonal cells are not adjacent
'''

In [9]:
#Construct an atlas of numbers
atlas = np.random.randint(0, 10, size=(100, 100))
#atlas = np.zeros(shape=(100, 100))

In [10]:
atlas[0][0] = 1
atlas[0][1] = 1
atlas[0][2] = 1
atlas[1][0] = 1

In [9]:
nationality_count = {i:0 for i in range(10)}

def incrementDict(element):
    nationality_count[element]+=1

def pairMatch(list_a, list_b):
    #Assume both lists have same length
    #You should count up the nationalities directly here otherwise you are passing through
    #the list twice
    pair_check = [incrementDict(element) for idx, element in enumerate(list_b) if element==list_a[idx]]
    
    return pair_check

In [10]:
row_matches = [pairMatch(atlas[idx], atlas[idx+1]) for idx, row in enumerate(atlas) if idx!=len(atlas)-1]

In [11]:
col_matches = [pairMatch(list(zip(*atlas))[idx], list(zip(*atlas))[idx+1]) for idx, row in \
               enumerate(list(zip(*atlas))) if idx!=len(atlas)-1]

In [12]:
nationality_count

{0: 206,
 1: 227,
 2: 208,
 3: 224,
 4: 182,
 5: 191,
 6: 196,
 7: 205,
 8: 185,
 9: 243}

In [13]:
#What if we just want to know how many nationalities there are?
#Not count their population?

#Possible algo

#1. Start at any point in matrix
#2. check four neighbors, are any a match? if not, junk the point and pick an adjacent point on the graph
#, we junk because we don't need to revisit it again
#3. if has a match, junk both the point and the adjacent matched point as we have found one pop type
#and don't need to find it again, step to any other point
#4. When picking new points, if point already in collection of nationalities just skip it

In [14]:
#nationality_set = set([])

In [15]:
#Have to watch out for wrap around
def checkAdjacent(start_x, start_y, nationality_set):
    new_nationality_found = -1
    
    if atlas[start_x][start_y] == atlas[start_x+1][start_y]:
        set([atlas[start_x][start_y]]).union(nationality_set)
        new_nationality_found = 0
        
    if atlas[start_x][start_y] == atlas[start_x][start_y+1]:
        set([atlas[start_x][start_y]]).union(nationality_set)
        new_nationality_found = 1

    if atlas[start_x][start_y] == atlas[start_x-1][start_y]:
        set([atlas[start_x][start_y]]).union(nationality_set)
        new_nationality_found = 2
    
    if atlas[start_x][start_y] == atlas[start_x][start_y-1]:
        set([atlas[start_x][start_y]]).union(nationality_set)
        new_nationality_found = 3
        
    return [new_nationality_found]

In [21]:
def exploreMatrix(start_x, start_y, nationality_set, test_count=0):
        
    if test_count>10000:
        return nationality_set
    
    #print (test_count)
    if start_x==0 or start_x==99 or start_y==0 or start_y==99:
        
        random_direction = np.random.randint(0, 4)
        if random_direction == 0: return exploreMatrix(start_x+1, start_y, nationality_set, test_count+1)
        if random_direction == 1: return exploreMatrix(start_x, start_y+1, nationality_set, test_count+1)
        if random_direction == 2: return exploreMatrix(start_x-1, start_y, nationality_set, test_count+1)
        if random_direction == 3: return exploreMatrix(start_x, start_y-1, nationality_set, test_count+1)
            
    #Check if already in nationality set
    if atlas[start_x][start_y] in nationality_set:
        
        random_direction = np.random.randint(0, 4)
        if random_direction == 0: return exploreMatrix(start_x+1, start_y, nationality_set, test_count+1)
        if random_direction == 1: return exploreMatrix(start_x, start_y+1, nationality_set, test_count+1)
        if random_direction == 2: return exploreMatrix(start_x-1, start_y, nationality_set, test_count+1)
        if random_direction == 3: return exploreMatrix(start_x, start_y-1, nationality_set, test_count+1)
    
    nationality_direction = checkAdjacent(start_x, start_y, nationality_set)
    
    step_directions = list(set([0, 1, 2, 3]) - set(nationality_direction))
    
    next_step = random.choice(step_directions)
    
    if next_step == 0: return exploreMatrix(start_x+1, start_y, nationality_set, test_count+1)
    if next_step == 1: return exploreMatrix(start_x, start_y+1, nationality_set, test_count+1)
    if next_step == 2: return exploreMatrix(start_x-1, start_y, nationality_set, test_count+1)
    if next_step == 3: return exploreMatrix(start_x, start_y-1, nationality_set, test_count+1)


    #Whats the break condition?
    #Has to be every node has been checked

In [7]:
matrix_graph = nx.Graph()

In [11]:
atlas

array([[1, 1, 1, ..., 6, 3, 9],
       [1, 8, 8, ..., 1, 5, 6],
       [1, 9, 0, ..., 1, 2, 4],
       ..., 
       [5, 3, 1, ..., 2, 0, 7],
       [3, 6, 2, ..., 1, 0, 2],
       [6, 1, 5, ..., 1, 3, 3]])

In [ ]:
'''
Question 4 

Remove alternate duplicate elements in a list

example: "you got beautiful eyes"
Output: ”you gtbeaiful es”

What if I remove all but the first appearance?
Pass through list only once
'''

In [12]:
string = 'you got beautiful eyes'

In [113]:
'''
Question 7

Find k largests elements in a list 
'''

'\nQuestion 7\n\nFind k largests elements in a list \n'

In [114]:
l = [1, 23, 12, 9, 30, 2, 50, 12, 49, 4, 26]

In [115]:
#suppose k=1

In [116]:
max_element = -1
for i in range(len(l)):
    #print(l[i])
    if l[i]>max_element: max_element=l[i]
        
print (max_element)

50


In [119]:
#suppose k is arbritary
k=4
#max_k = sorted(l[:k])
max_k = l[:k]
for i in range(k, len(l), 1):
    if l[i]>max_k[0]: 
        max_k[0]=l[i]
        max_k = sorted(max_k)

In [120]:
max_k

[26, 30, 49, 50]

In [ ]:
'''
Question 6

Given a matrix, rotate it 90 degrees counter-clockwise in place
 1  2  3  4 
 5  6  7  8 
 9 10 11 12 
13 14 15 16 

Output:
 4  8 12 16 
 3  7 11 15 
 2  6 10 14 
 1  5  9 13
'''

In [186]:
matrix = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13, 14, 15, 16]])

In [197]:
n_size = len(matrix[0])

In [ ]:
#The hardest part about this problem is the indexing
#Its obvious there are cycles in a square matrix
#the problem is knowing how to index the positions correctly
#and realizing there are four swaps you have to make per loop

In [198]:
#The number of "square cycles is always half rounded down the size of the matrix
for cycle in range(n_size//2):
    #if cycle==0: continue
    #In each cycle you have to move all the elements, going around in a circle
    #Each cycle is smaller then the prior cycle (going from the outside of the matrix inside)
    for x in range(cycle, n_size-cycle-1, 1):
        
        temp = matrix[cycle][x]
        #Move top right to top left
        matrix[cycle][x] = matrix[x][n_size-1-cycle]
        #move bottom right to top right
        matrix[x][n_size-1-cycle] = matrix[n_size-1-cycle][n_size-1-x]
        #move bottom left to bottom right
        matrix[n_size-1-cycle][n_size-1-x] = matrix[n_size-1-x][cycle]
        #move top left to bottom left
        matrix[n_size-1-x][cycle] = temp

In [199]:
matrix

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [72]:
#Without using inplace method
matrix_new = np.zeros(shape=(3, 3))

for i in range(len(matrix)):
    matrix_new[:,i] = sorted(matrix[i], reverse=True)

In [ ]:
'''
Question 7

Next Greater Element
Given an array, print the Next Greater Element (NGE) for every element. 
The Next greater Element for an element x is the first greater element on the right side of x in array. 
Elements for which no greater element exist, consider next greater element as -1.

Example:

[4, 5, 2, 25}

Element       NGE
   4      -->   5
   5      -->   25
   2      -->   25
   25     -->   -1
'''

In [213]:
elements = [13, 7, 6, 12]
nge = []

In [214]:
sorted_elements = sorted(elements)

In [215]:
sorted_elements, elements

([6, 7, 12, 13], [13, 7, 6, 12])

In [216]:
for i in range(len(elements)):
    found_nge = 0
    for j in range(i, len(elements), 1):
        if elements[j]>elements[i]:
            print (elements[i], elements[j])
            found_nge = 1
            break
    if found_nge == 0:
        print (elements[i], -1)            

13 -1
7 12
6 12
12 -1


In [234]:
#Faster solution

In [230]:
# Python program to print next greater element using stack
 
def createStack():
    stack = []
    return stack
 
def isEmpty(stack):
    return len(stack) == 0
 
def push(stack, x):
    stack.append(x)
 
def pop(stack):
    if isEmpty(stack):
        print("Error : stack underflow")
    else:
        return stack.pop()

In [231]:
def printNGE(arr):
    s = createStack()
    element = 0
    next = 0
 
    # push the first element to stack
    push(s, arr[0])
 
    # iterate for rest of the elements
    for i in range(1, len(arr), 1):
        next = arr[i]
 
        if isEmpty(s) == False:
 
            # if stack is not empty, then pop an element from stack
            element = pop(s)
 
            '''If the popped element is smaller than next, then
                a) print the pair
                b) keep popping while elements are smaller and
                   stack is not empty '''
            while element < next :
                print(str(element)+ " -- " + str(next))
                if isEmpty(s) == True :
                    break
                element = pop(s)
 
            '''If element is greater than next, then push
               the element back '''
            if  element > next:
                push(s, element)
 
        '''push next to stack so that we can find
           next greater for it '''
        push(s, next)
 
    '''After iterating over the loop, the remaining
       elements in stack do not have the next greater
       element, so print -1 for them '''
 
    while isEmpty(s) == False:
            element = pop(s)
            next = -1
            print(str(element) + " -- " + str(next))

In [233]:
printNGE([3, 2, 4, 2])

2 -- 4
3 -- 4
2 -- -1
4 -- -1


In [ ]:
'''
Question 8

Given an array of positive numbers, find the maximum sum of a subsequence with the 
constraint that no 2 numbers in the sequence should be adjacent in the array. 
So 3 2 7 10 should return 13 (sum of 3 and 10) or 3 2 5 10 7 should return 15 (sum of 3, 5 and 7).
Answer the question in most efficient way.

Examples:

Input : arr[] = {5, 5, 10, 100, 10, 5}
Output : 110

Input : arr[] = {1, 2, 3}
Output : 4

Input : arr[] = {1, 20, 3}
Output : 20
'''

In [425]:
array = [5, 5, 10, 40, 3, 1]

In [426]:
#Dynamic programming problem, have to keep track of two running sums.
#Tricky problem
#Inclusive: The best possible sum if I include the current number
#Exclusive: The best possible sum if I don't include the current number

incl = 0
excl = 0

for index, i in enumerate(array):
    #print (index, 'step0:', i, incl, excl)
    new_excl = incl
    # Current max including i
    incl = excl + i
    #print (index, 'step1:', i, incl, excl)

    excl = new_excl
    #print (index, 'step2:', i, incl, excl)

In [427]:
'''
Question 9

Given two strings str1 and str2 and below operations 
that can performed on str1. Find minimum number of edits (operations) required to convert ‘str1’ into ‘str2’.

Insert
Remove
Replace
All of the above operations are of equal cost.

Example:

Input:   str1 = "geek", str2 = "gesek"
Output:  1
We can convert str1 into str2 by inserting a 's'.

Input:   str1 = "cat", str2 = "cut"
Output:  1
We can convert str1 into str2 by replacing 'a' with 'u'.

Input:   str1 = "sunday", str2 = "saturday"
Output:  3
Last three and first characters are same.  We basically
need to convert "un" to "atur".  This can be done using
below three operations. 
Replace 'n' with 'r', insert t, insert a
'''

(46, 18)

In [6]:
str1 = 'geek'
str2 = 'gesekt'

In [7]:
#Initial position has to be at back of string
def editDistance(str1, str2, str1_pos, str2_pos, score=0):
    #These two are the crucial "bottoms" of the recursive function and hard to understand
    if str1_pos==0:
        return str2_pos
    if str2_pos==0:
        return str1_pos
    
    #print (str1[str1_pos], str2[str2_pos])
    if str1[str1_pos]==str2[str2_pos]:
        return editDistance(str1, str2, str1_pos-1, str2_pos-1)
    else:
        #Why is this 1+ needed? maybe you need the 1 because the element positions start counting from 0 and not 1?
        return 1+min(editDistance(str1, str2, str1_pos-1, str2_pos), editDistance(str1, str2, str1_pos, str2_pos-1), \
            editDistance(str1, str2, str1_pos-1, str2_pos-1))

In [8]:
editDistance(str1, str2, len(str1)-1, len(str2)-1)

2

In [9]:
#Dynamic programming solution

In [44]:
str1='sunday'
str2='saturday'

In [45]:
edit_matrix= [[0 for i in range(len(str2)+1)] for j in range(len(str1)+1)]

In [46]:
edit_matrix

[[0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [47]:
for idx_1 in range(len(str1)+1):
    for idx_2 in range(len(str2)+1):
        if idx_1==0:
            edit_matrix[idx_1][idx_2] = idx_2 #this means it takes j moves to transform blank to w/e j is (j could be zero)
        
        elif idx_2==0:
            edit_matrix[idx_1][idx_2] = idx_1 #this means the reverse, if j is zero it takes i  moves to transform it from blank
            
        elif str1[idx_1-1] == str2[idx_2-1]: #in this case always take diagonal element before
            edit_matrix[idx_1][idx_2] = edit_matrix[idx_1-1][idx_2-1]
        
        else:
            #other wise its one move (which is the cost of modifying the current char to be the same) + the least amount of 
            #moves from the prior char position, the least amount of moves from the previous char position given all possible
            #ways of moving is giving by replace, add, and modify
            edit_matrix[idx_1][idx_2] = 1 + min(edit_matrix[idx_1-1][idx_2-1], 
                                                edit_matrix[idx_1][idx_2-1], 
                                                edit_matrix[idx_1-1][idx_2])

In [48]:
edit_matrix

[[0, 1, 2, 3, 4, 5, 6, 7, 8],
 [1, 0, 1, 2, 3, 4, 5, 6, 7],
 [2, 1, 1, 2, 2, 3, 4, 5, 6],
 [3, 2, 2, 2, 3, 3, 4, 5, 6],
 [4, 3, 3, 3, 3, 4, 3, 4, 5],
 [5, 4, 3, 4, 4, 4, 4, 3, 4],
 [6, 5, 4, 4, 5, 5, 5, 4, 3]]

In [ ]:
'''
Question 10

The Stock Span Problem

The stock span problem is a financial problem where 
we have a series of n daily price quotes for a stock and 
we need to calculate span of stock’s price for all n days. 

The span Si of the stock’s price on a given day i is defined as the 
maximum number of consecutive days just before the given day, 
for which the price of the stock on the current day is less than or 
equal to its price on the given day.
For example, if an array of 7 days prices is given as {100, 80, 60, 70, 60, 75, 85}, 
then the span values for corresponding 7 days are {1, 1, 1, 2, 1, 4, 6}
'''

In [98]:
stock_price = [100, 80, 60, 70, 60, 75, 85]
stock_price = [10, 4, 5, 90, 120, 80]

In [99]:
span = [-1 for i in range(len(stock_price))]

In [100]:
stock_price

[10, 4, 5, 90, 120, 80]

In [101]:
for idx_i in range(len(stock_price)):
    if idx_i==0: #Assuming this a default state
        span[0] = 1
    else:            
        span_sum = 0
        for idx_j in reversed(range(0, len(stock_price[:idx_i]), 1)):
            if stock_price[idx_i]<stock_price[idx_j]:
                span[idx_i] = (idx_i-idx_j)
                break

In [ ]:
'''
Question 11

a) Construct a binary tree class

b) Given the root of a binary tree and a number,
write a function that returns the node with the number or null if the number is not found.
'''

In [2]:
#a) The constructor creates one "fork", the fork is then duplicated to construct a tree
#Therefore to construct the tree one has to recursively call the constructor!
#Have to change the way I think about the problem

class BinaryTree():

    def __init__(self,rootid):
        self.left = None
        self.right = None
        self.rootid = rootid

    def getLeftChild(self):
        return self.left
    
    def getRightChild(self):
        return self.right
    
    def setNodeValue(self,value):
        self.rootid = value
    
    def getNodeValue(self):
        return self.rootid

In [5]:
tree = BinaryTree(3)

In [6]:
tree.left = BinaryTree(2)

In [7]:
tree.right = BinaryTree(1)

In [8]:
tree.left.left = BinaryTree(4)
tree.left.right = BinaryTree(1)

In [9]:
tree.right.left = BinaryTree(9)
tree.right.right = BinaryTree(8)

In [10]:
#b) Write a function that traverses every node in the tree

In [30]:
#DO NOT CALL RETURN!
#You are fundamentally misunderstanding how return works in a recursive function
#If you call return, you are asking to terminate the recursive call, otherwise the function will
#"boomerang" back which is the effect you were looking for!

def findNode(tree, num, found, layer=0):
    
    if tree.getNodeValue() is None:
        return None
    elif tree.getNodeValue()==num:
        print ('Number %d found' % num)
    else:
        print (tree.getNodeValue())
        if tree.right is not None:
            findNode(tree.getRightChild(), num, found, layer+1)
        if tree.left is not None:
            findNode(tree.getLeftChild(), num, found, layer+1)    

In [33]:
findNode(tree, 8, 0, 0)

3
1
Number 8 found
9
2
1
4


In [40]:
#Why does return not work.
def findNode(tree, layer=0):

    print (tree.getNodeValue())
    if tree.right is not None:
        return findNode(tree.getRightChild(), layer+1)
    #Notice the function is the same regardless if you comment this bottom part in or out
    #Because as soon as you hit the return statement the current iteration ends!!
#    if tree.left is not None:
#        return findNode(tree.getLeftChild(), layer+1)    

In [41]:
findNode(tree, layer=0)

3
1
8


In [ ]:
'''
Spiral pattern, write a function that produces the following pattern:
n=3 123
    894  
    765
n=4 1   2  3 4
    12 13 14 5
    11 16 15 6
    10  9  8 7
'''

In [ ]:
#try and do odd n

In [ ]:
for i in range(3):
    for j in range(3):
        

In [6]:
'''
One edit away

Write a function that returns whether two strings are exactly one edit away
An edit is:
1.Inserting one character anywhere in the word (including at the beginning and end)
2. Removing one character
3. Replacing one character
OneEditApart("cat", "dog") = false
OneEditApart("cat", "cats") = true
OneEditApart("cat", "cut") = true
OneEditApart("cat", "cast") = true
OneEditApart("cat", "at") = true
OneEditApart("cat", "act") = false #key to note
'''

In [105]:
def OneEditApart(str1, str2):
    
    if abs(len(str1)-len(str2))>1:
        return False
    else:        
        if len(str1)==len(str2):
            n_edits=0
            for idx in range(len(str1)):
                if str1[idx]==str2[idx]:
                    pass
                else:
                    n_edits+=1
        else:
            #if not the same length, they can at most differ by length one
            #The thing to check now is are they more then one edit away?
            #For sure they cannot be 0 edits away anymore
            n_edits=1
            #Always want str1 to be the smaller one
            if len(str1)>len(str2):
                str1, str2=str2, str1
            for idx in range(min(len(str1), len(str2))):                    
                if str1[idx]==str2[idx]:
                    pass
                elif str1[idx]==str2[idx+1]:
                    pass
                else:
                    n_edits+=1                            
        
        return n_edits==1        

In [107]:
OneEditApart('cat', 'cat')

False

In [ ]:
'''
Implement a function that outputs the Look and Say sequence: 
1
11
21
1211
111221
312211
13112221
1113213211
31131211131221
13211311123113112211
The next sequence is generated by reading the last one
'''

In [ ]:
#Lets count the number of occurrences of a numbers from left to right

In [172]:
def generate_look_say_sequence(current_seq):
    sequences = []
    idx=0
    while idx<len(current_seq):    
        current_char = current_seq[idx]
        current_ptr = idx
        sub_seq=[]
        while current_ptr<len(current_seq):
            if current_seq[current_ptr]==current_char:            
                sub_seq.append(current_seq[current_ptr])
                current_ptr+=1
            else:
                break
        sequences.append(sub_seq)
        idx+=len(sub_seq)
    
    seq_counting = [np.unique(sub_seq, return_counts=True) for sub_seq in sequences]
    
    return ''.join([str(i[1][0]) + str(i[0][0]) for i in seq_counting])

In [178]:
generate_look_say_sequence(generate_look_say_sequence(generate_look_say_sequence(generate_look_say_sequence(generate_look_say_sequence('1')))))

'312211'

In [179]:
'''
Given a string A.

Return the string A after reversing the string word by word.

NOTE:

    A sequence of non-space characters constitutes a word.

    Your reversed string should not contain leading or trailing spaces, even if it is present in the input string.

    If there are multiple spaces between words, reduce them to a single space in the reversed string.

Input 1:
    A = "the sky is blue"
Output 1:
    "blue is sky the"

Input 2:
    A = "this is ib"
Output 2:
    "ib is this"
'''

'\nGiven a string A.\n\nReturn the string A after reversing the string word by word.\n\nNOTE:\n\n    A sequence of non-space characters constitutes a word.\n\n    Your reversed string should not contain leading or trailing spaces, even if it is present in the input string.\n\n    If there are multiple spaces between words, reduce them to a single space in the reversed string.\n\nInput 1:\n    A = "the sky is blue"\nOutput 1:\n    "blue is sky the"\n\nInput 2:\n    A = "this is ib"\nOutput 2:\n    "ib is this"\n'

In [184]:
def reverse_string(string):
    reversed_words = []
    for word in reversed(string.split(' ')):
        reversed_words.append(word)
    return ' '.join(reversed_words).strip()

In [185]:
reverse_string("the sky is blue ")

'blue is sky the'

In [ ]:
'''
Stock span problem buy-sell 
If you were only permitted to complete at most one transaction 
(ie, buy one and sell one share of the stock), design an algorithm to find the maximum profit.
Return the maximum possible profit.

Problem Constraints

1 <= A[i] <= 1e7

Example Input

Input 1: A = [1, 2]

Input 2: A = [1, 4, 5, 2, 4]

Explanation 1: Buy the stock on day 0, and sell it on day 1.

Explanation 2: Buy the stock on day 0, and sell it on day 2.
'''

In [260]:
A=[201, 4, 5, 2, 4, 99, 13, 10, 190, 191, 11, 10, 1000000]

In [261]:
#Naive solution
#Enumerate through all different combinations
best_profit = 0
dates=[0,0]
for idx_buy in range(len(A)):
    buy_price = A[idx_buy]
    for idx_sell in range(idx_buy+1, len(A), 1):
        sell_price = A[idx_sell]
        if sell_price-buy_price>best_profit:
            best_profit=sell_price-buy_price
            dates=[idx_buy, idx_sell]

In [262]:
dates

[3, 12]

In [263]:
#Alternative solution
#Suppose you sort the list and returned the index position of the sorted results
#Then just take the arguments of the sorted list at the beginning and end

In [264]:
def merge_sort(span, indices):
    '''
    merge_sort
    
    return the indices of the sorted results
    '''
    if len(span)==1:        
        return [span[0]], [indices[0]]
    elif len(span)==2:
        if span[0]>span[1]:
            return [span[1], span[0]], [indices[1], indices[0]]
        else:
            return [span[0], span[1]],[indices[0], indices[1]]
    else:
        span_left = span[:len(span)//2]
        span_right = span[len(span)//2:]
        indices_left = indices[:len(span)//2]
        indices_right = indices[len(span)//2:]

        left_best_span, left_best_indices = merge_sort(span_left, indices_left)
        right_best_span, rigth_best_indices = merge_sort(span_right, indices_right)
        
        #Merge the left and right spans and sort 
        #How do i merge?
        left_right_span = left_best_span + right_best_span
        left_right_indices = left_best_indices + rigth_best_indices
        sorted_span = []
        sorted_indices = []
        
        while len(left_right_span)!=0:
            lowest_value = min(left_right_span)
            lowest_index = left_right_indices[left_right_span.index(lowest_value)]
            
            sorted_span.append(lowest_value)
            sorted_indices.append(lowest_index)
            
            left_right_span.remove(lowest_value)
            left_right_indices.remove(lowest_index)
        
        return sorted_span, sorted_indices

In [265]:
#modify the merge sort to return the args instead of the values

In [266]:
A_indices =[i for i in range(len(A))]

In [267]:
#Ended up writing merge sort instead...
sorted_A, sorted_args = merge_sort(A, A_indices)

In [268]:
sorted_A

[2, 4, 4, 5, 10, 10, 11, 13, 99, 190, 191, 201, 1000000]

In [284]:
#More efficient merge sort
def merge_sort(span):
    '''
    merge_sort
    
    return the indices of the sorted results
    '''
    if len(span)==1:        
        return [span[0]]
    elif len(span)==2:
        if span[0]>span[1]:
            return [span[1], span[0]]
        else:
            return [span[0], span[1]]
    else:
        span_left = span[len(span)//2:]
        span_right = span[:len(span)//2]

        left_best_span = merge_sort(span_left)
        right_best_span = merge_sort(span_right)
        
        #Merge the left and right spans and sort 
        #How do i merge?
        #left_right_span = left_best_span + right_best_span
        
        sorted_span = []
        left_idx=0
        right_idx=0
        while left_idx<len(left_best_span) and right_idx<len(right_best_span):
            
            if left_best_span[left_idx]<right_best_span[right_idx]:

                sorted_span.append(left_best_span[left_idx]) 
                left_idx+=1
            else:
                sorted_span.append(right_best_span[right_idx]) 
                right_idx+=1
        
        #Compensate for the last values that were not incremented to
        if left_idx==len(left_best_span):
            sorted_span+=right_best_span[right_idx:]
        else:
            sorted_span+=left_best_span[left_idx:]
        return sorted_span

In [287]:
'''
Find largest distance
Given an arbitrary unweighted rooted tree which consists of N (2 <= N <= 40000) nodes. 
The goal of the problem is to find largest distance between two nodes in a tree. 
Distance between two nodes is a number of edges on a path between the nodes 
(there will be a unique path between any pair of nodes since it is a tree). 
The nodes will be numbered 0 through N - 1.

The tree is given as an array P, there is an edge between nodes P[i] and i (0 <= i < N). 
Exactly one of the i’s will have P[i] equal to -1, it will be root node.

Example:
If given P is [-1, 0, 0, 0, 3], then node 0 is the root and the whole tree looks like this: 

      0
   /  |  \
  1   2   3
           \
            4  

One of the longest path is 1 -> 0 -> 3 -> 4 and its length is 3,
thus the answer is 3. Note that there are other paths with maximal distance. 
'''

[-10, -10, 0, 0, 10, 10, 123]

In [ ]:
#Nuances
#We are only discussing trees not graphs!
#First problem: P must be converted into a adjacency or some structure that let's one query for neighbors
#Second problem: Understand the concept of breadth first search and how it can used to calculate the diameter of a BT

In [288]:
#Cool way to express an undirected Tree
P = [-1, 0, 0, 0, 3]

In [539]:
#Convert to adj_list representation or any representaton that lets you query the neighbors
adj_list = {}
for idx in range(len(P)):
    if P[idx]==-1:
        continue
    else:
        if P[idx] not in adj_list.keys():
            adj_list[P[idx]] = [idx]
        else:
            adj_list[P[idx]].append(idx)
        
        if idx not in adj_list.keys():
            adj_list[idx] = [P[idx]]
        else:
            adj_list[idx].append(P[idx])

In [542]:
#Traverse the graph once from a initial node and then traverse from the farthest node relative to the initial node
#counting the paths (counting the paths is tricky part)

def bfs_traverse_nodes(adj_list, initial_node):

    visited_nodes= [initial_node]
    current_queue = [initial_node]
    dist_from_initial_node = {initial_node:0}
    while len(current_queue)!=0:

        current_node = current_queue.pop(0) #remove from the front as it is a queue   
        current_neighbors = adj_list[current_node]
        
        for neighbor in current_neighbors:
            
            if neighbor not in visited_nodes:                
                current_queue.append(neighbor)
                dist_from_initial_node[neighbor] = dist_from_initial_node[current_node] + 1
                visited_nodes.append(neighbor)
                
    return visited_nodes, dist_from_initial_node

In [543]:
_, dist_from_initial_node = bfs_traverse_nodes(adj_list, 0)

In [544]:
pivot_node = {j:i for i, j in dist_from_initial_node.items()}[max(dist_from_initial_node.values())]

In [547]:
dist_from_initial_node

{0: 0, 1: 1, 2: 1, 3: 1, 4: 2}

In [549]:
_, dist_from_pivot_node = bfs_traverse_nodes(adj_list, pivot_node)

In [550]:
final_node = {j:i for i, j in dist_from_pivot_node.items()}[max(dist_from_pivot_node.values())]

In [5]:
# A class for constructing nodes in a binary tree
class Node: 
  
    # Constructor to create a new node 
    def __init__(self, data): 
        self.data = data  
        self.left = None
        self.right = None  

In [950]:
#construct a binary tree by iteratively adding nodes
root = Node(4) 
root.left = Node(2) 
root.right = Node(5) 
root.right.right = Node(-7) 
root.left.left = Node(5) 
root.left.right = Node(3) 
root.left.right.right = Node(7)
root.left.right.left = Node(19)

In [959]:
def in_order_t(node):
    if node is not None:
        in_order_t(node.left)
        print (node.data)
        in_order_t(node.right)

def pre_order_t(node):
    if node is not None:
        print (node.data)
        pre_order_t(node.left)        
        pre_order_t(node.right)        
        
def post_order_t(node):
    if node is not None:
        
        post_order_t(node.left)        
        post_order_t(node.right)                
        print (node.data)

In [962]:
post_order_t(root)

5
19
7
3
2
-7
5
4


In [ ]:
'''
Verify if a binary tree is a binary search tree
''' 
INT_MAX = 4294967296
INT_MIN = -4294967296
  

#Returns true if the given tree is a binary search tree 
#(efficient version) 
def isBST(node): 
    return (isBSTUtil(node, INT_MIN, INT_MAX)) 
  
# Retusn true if the given tree is a BST and its values 
# >= min and <= max 
def isBSTUtil(node, mini, maxi): 
      
    # An empty tree is BST 
    if node is None: 
        return True
  
    # False if this node violates min/max constraint 
    if node.data < mini or node.data > maxi: 
        return False
  
    # Otherwise check the subtrees recursively 
    # tightening the min or max constraint 
    return (isBSTUtil(node.left, mini, node.data -1) and
          isBSTUtil(node.right, node.data+1, maxi)) 

In [ ]:
if (isBST(root)): 
    print ("Is BST")
else: 
    print ("Not a BST")  

In [ ]:
'''
Quicksort

code a quicksort algo

why does quicksort start at -1?
'''

In [575]:
def partition(arr,low,high): 
    i = ( low-1 )         # index of smaller element 
    pivot = arr[high]     # pivot 
  
    for j in range(low , high): 
        print('j:%d, arr[j]:%d, pivot:%d, before arr:%s' % (j, arr[j], pivot, arr))
        # If current element is smaller than the pivot 
        if   arr[j] < pivot: 
          
            # increment index of smaller element 
            i = i+1 
            arr[i],arr[j] = arr[j],arr[i] 
        print('j:%d, arr[j]:%d, pivot:%d, after arr:%s' % (j, arr[j], pivot, arr))
    arr[i+1],arr[high] = arr[high],arr[i+1] 
    return ( i+1 ) 
  
def quickSort(arr,low,high): 
    if low < high: 
  
        # pi is partitioning index, arr[p] is now 
        # at right place 
        pi = partition(arr,low,high) 
  
        # Separately sort elements before 
        # partition and after partition 
        quickSort(arr, low, pi-1) 
        quickSort(arr, pi+1, high) 
  

In [576]:
A=[100, -1, 203, 123,0,1,2,39, 10]

In [577]:
quickSort(A, 0, len(A)-1)

j:0, arr[j]:100, pivot:10, before arr:[100, -1, 203, 123, 0, 1, 2, 39, 10]
j:0, arr[j]:100, pivot:10, after arr:[100, -1, 203, 123, 0, 1, 2, 39, 10]
j:1, arr[j]:-1, pivot:10, before arr:[100, -1, 203, 123, 0, 1, 2, 39, 10]
j:1, arr[j]:100, pivot:10, after arr:[-1, 100, 203, 123, 0, 1, 2, 39, 10]
j:2, arr[j]:203, pivot:10, before arr:[-1, 100, 203, 123, 0, 1, 2, 39, 10]
j:2, arr[j]:203, pivot:10, after arr:[-1, 100, 203, 123, 0, 1, 2, 39, 10]
j:3, arr[j]:123, pivot:10, before arr:[-1, 100, 203, 123, 0, 1, 2, 39, 10]
j:3, arr[j]:123, pivot:10, after arr:[-1, 100, 203, 123, 0, 1, 2, 39, 10]
j:4, arr[j]:0, pivot:10, before arr:[-1, 100, 203, 123, 0, 1, 2, 39, 10]
j:4, arr[j]:100, pivot:10, after arr:[-1, 0, 203, 123, 100, 1, 2, 39, 10]
j:5, arr[j]:1, pivot:10, before arr:[-1, 0, 203, 123, 100, 1, 2, 39, 10]
j:5, arr[j]:203, pivot:10, after arr:[-1, 0, 1, 123, 100, 203, 2, 39, 10]
j:6, arr[j]:2, pivot:10, before arr:[-1, 0, 1, 123, 100, 203, 2, 39, 10]
j:6, arr[j]:123, pivot:10, after arr:[

In [24]:
0b1111<<1

30

In [ ]:
'''
Find the container with the most water

Given n non-negative integers a1, a2, ..., an,
where each represents a point at coordinate (i, ai).
'n' vertical lines are drawn such that the two endpoints of line i is at (i, ai) and (i, 0).

Find two lines, which together with x-axis forms a container, such that the container contains the most water.

Your program should return an integer which corresponds to the maximum area of water that can be contained 
( Yes, we know maximum area instead of maximum volume sounds weird. But this is 2D plane 
we are working with for simplicity ).


Note: You may not slant the container. <---I guess this means you cannot have diagonal lids?

Input : [1, 5, 4, 3]
Output : 6

Explanation : 5 and 3 are distance 2 apart. So size of the base = 2. Height of container = min(5, 3) = 3. 
So total area = 3 * 2 = 6
'''

In [677]:
coords = [1, 5, 4, 3]

In [678]:
#Start with the box with the largest base size and work your way down

In [679]:
#Simple solution, enumerate through all boxes
def enumerate_boxes(box_coords):
    
    '''
    enumerate_boxes
    
    Go through a list considering all boxes from biggest to smallest
    '''
    optimal_base = None
    optimal_height = None
    largest_box = 0
    for base_size in reversed(range(1, len(coords)+1, 1)): #Forgot +1?
        #find best height
        #Boxes are contiguous
        print(base_size)
        n_possible_boxes = (len(coords)//base_size) + (len(coords)%base_size)
        for chunk in range(0, n_possible_boxes, 1):
            base_coords = coords[chunk:chunk+base_size]
            print(base_coords)
            #can't have a slanted top, so we have to choose the minimum height
            #Can't take values in between otherwise that doesn't form a box
            best_height = min(base_coords[0], base_coords[-1]) 
            best_area = best_height*(base_size-1) #Need negative since the base has to begin from the position
            if best_area>largest_box: 
                largest_box=best_area
                optimal_height = best_height
                optimal_base = base_coords
    
    return [largest_box, optimal_height, optimal_base]

In [680]:
enumerate_boxes(coords)

4
[1, 5, 4, 3]
3
[1, 5, 4]
[5, 4, 3]
2
[1, 5]
[5, 4]
1
[1]
[5]
[4]
[3]


[6, 3, [5, 4, 3]]

In [663]:
#How can we optimize?
#Notice after finishing one box, the best sub-box has the wall height of the maximum of the two current walls
#with a intermediate wall of at least the height of the taller of the two current walls

In [664]:
left_wall = 0
right_wall = len(coords)-1
best_box = 0

In [665]:
while (left_wall<right_wall): #Box has to be atleast width 1
    
    current_height = min(coords[left_wall], coords[right_wall])
    current_width = right_wall-left_wall
    current_area = current_height*current_width
    if current_area>best_box: best_box=current_area
    
    #if the left wall is lower then the right wall, no point in searching to the left
    
    if left_wall<right_wall:
        left_wall+=1
    else:
        right_wall-=1
    

In [799]:
'''
You are given two linked lists representing two non-negative numbers. 
The digits are stored in reverse order and each of their nodes contain a single digit. 
Add the two numbers and return it as a linked list.

Input: (2 -> 4 -> 3) + (5 -> 6 -> 4)
Output: 7 -> 0 -> 8

    342 + 465 = 807

Make sure there are no trailing zeros in the output list
So, 7 -> 0 -> 8 -> 0 is not a valid response even though the value is still 807.
'''

'\nYou are given two linked lists representing two non-negative numbers. \nThe digits are stored in reverse order and each of their nodes contain a single digit. \nAdd the two numbers and return it as a linked list.\n\nInput: (2 -> 4 -> 3) + (5 -> 6 -> 4)\nOutput: 7 -> 0 -> 8\n\n    342 + 465 = 807\n\nMake sure there are no trailing zeros in the output list\nSo, 7 -> 0 -> 8 -> 0 is not a valid response even though the value is still 807.\n'

In [ ]:
#essence of a linked list is that it can only be traversed one way

In [800]:
a = [2, 4, 3]
b = [5, 6, 4]

In [4]:
class Node(object):
    def __init__(self):
        self.data = None # contains the data
        self.next = None # contains the reference to the next node

In [914]:
class LinkedList:
    def __init__(self):
        self.cur_node = None

    def add_node(self, data):
        new_node = Node() # create a new node
        new_node.data = data
        new_node.next = self.cur_node # link the new node to the 'previous' node.
        self.cur_node = new_node #  set the current node to the new one.

    def list_print(self):
        node = self.cur_node # cant point to ll!
        while node:
            print (node.data)
            node = node.next

In [934]:
642+5465

6107

In [929]:
a = LinkedList()
a.add_node(6)
a.add_node(4)
a.add_node(2)

b = LinkedList()
b.add_node(5)
b.add_node(4)
b.add_node(6)
b.add_node(5)

c = LinkedList()

In [930]:
#Can we assume the two nodes are the same length?

In [931]:
def add_linked_lists():
    remainder = 0 
    current_a = a.cur_node
    current_b = b.cur_node    

    queue = []
    while True:
        if current_a is None:        
            current_sum = current_b.data
        elif current_b is None:        
            current_sum = current.a.data
        else:        
            current_sum = current_a.data + current_b.data

        if current_sum<10:        
            queue.append(current_sum+remainder)
            remainder = 0  
        else:#Largest value is 9+9=18        
            queue.append(current_sum%10+remainder)
            remainder = 1

        if current_a is None:        
            current_b=current_b.next
        elif current_b is None:        
            current_a=current_a.next
        else:        
            current_b=current_b.next
            current_a=current_a.next    

        if current_a is None and current_b is None:break

    while queue:
        c.add_node(queue.pop())

In [936]:
'''
Find the intersection of two sorted arrays.
OR in other words,
Given 2 sorted arrays, find all the elements which occur in both the arrays.

Example :

Input : 
    A : [1 2 3 3 4 5 6]
    B : [3 3 5]

Output : [3 3 5]

Input : 
    A : [1 2 3 3 4 5 6]
    B : [3 5]

Output : [3 5]
'''

'\nFind the intersection of two sorted arrays.\nOR in other words,\nGiven 2 sorted arrays, find all the elements which occur in both the arrays.\n\nExample :\n\nInput : \n    A : [1 2 3 3 4 5 6]\n    B : [3 3 5]\n\nOutput : [3 3 5]\n\nInput : \n    A : [1 2 3 3 4 5 6]\n    B : [3 5]\n\nOutput : [3 5]\n'

In [ ]:
#Bidirectional Search
#Implement a bidirectional search

In [ ]:
'''
Given a sorted list of unique integers, construct a binary search tree with minimal height
I think there is actually only one such tree thus it is unique
'''

In [983]:
a = [-7, -1, 0, 2, 10, 15, 16]

In [995]:
def min_tree(a):
    
    if len(a)==1: return Node(a[0])
    elif len(a)==0: return Node(None)
    
    else:
        mid_point = len(a)//2
        data = a[mid_point]
        left_a = a[:mid_point]
        right_a = a[mid_point+1:]
        root = Node(data)
        
        root.left = min_tree(left_a)
        root.right = min_tree(right_a)
        
        return root        

In [996]:
tree = min_tree(a)

In [997]:
in_order_t(tree)

-7
-1
0
2
10
15
16


In [999]:
'''
Given a binary tree write a algorithm that checks if it is balanced 
Balanced means that the left and right subbranches of any node does not differ by more then
1 in height.
'''

'\nGiven a binary tree write a algorithm that checks if it is balanced \nBalanced means that the left and right subbranches of any node does not differ by more then\n1 in height.\n'

In [3]:
#Sample tree
root = Node(1) 
root.left = Node(2) 
root.right = Node(3) 
root.left.left = Node(4) 
root.left.right = Node(5) 
root.right.left = Node(6) 
root.left.left.left = Node(7)
root.left.left.left.left = Node(7)

NameError: name 'Node' is not defined

In [1002]:
# utility class to pass height object 
class Height: 
    def __init__(self): 
        self.height = 0
  
# helper function to check if binary 
# tree is height balanced 
def isBalanced(root, height): 
      
    # lh and rh to store height of  
    # left and right subtree 
    lh = Height() 
    rh = Height() 
  
    # Base condition when tree is  
    # empty return true 
    if root is None: 
        return True
  
    # l and r are used to check if left 
    # and right subtree are balanced 
    l = isBalanced(root.left, lh) 
    r = isBalanced(root.right, rh) 
  
    # height of tree is maximum of  
    # left subtree height and 
    # right subtree height plus 1 
    height.height = max(lh.height, rh.height) + 1
  
    if abs(lh.height - rh.height) <= 1: 
        return l and r 
  
    # if we reach here then the tree  
    # is not balanced 
    return False  

In [1007]:
height = Height()

In [1008]:
isBalanced(root, height)

False

In [1123]:
#Sample tree
root = Node(3) 
root.left = Node(4) 
root.right = Node(5) 
root.left.left = Node(7) 
root.left.left.left = Node(-1)
root.left.left.right = Node(9)
root.left.left.right.left = Node(12)
root.left.left.right.right = Node(13)

In [1124]:
'''
Common ancestor

Given two nodes find the first common ancestor of them both.

Insight: If the two nodes are in different subtrees then the current node is the best common ancestor
otherwise there is a even more "common" common ancestor
'''

'\nCommon ancestor\n\nGiven two nodes find the first common ancestor of them both.\n\nInsight: If the two nodes are in different subtrees then the current node is the best common ancestor\notherwise there is a even more "common" common ancestor\n'

In [1125]:
#Let A be the two nodes

In [1249]:
def check_node(root, n):
    
    '''
    check if a node exists from the a given root 
    based on the value of the node
    '''
    
    
    if root is None: return False    
    if root.data == n: return True
    check_left=check_node(root.left, n) #in order to return the result this has to equal something
    
    check_right=check_node(root.right, n)
    
    return max(check_left, check_right)

In [1263]:
#The key is recognizing if they two nodes are on opposite sides, then the current root is the
#lowest common ancestor
def best_ancestor(root, n1, n2):
    '''
    We will assume both nodes definitely exist in the tree
    and there are no duplicate nodes
    '''    
    
    if root is None: return None
    
    #This is what you are missing
    if root.data == n1:return n1
    if root.data == n2:return n2
    
    check_left_n1 = check_node(root.left, n1)
    check_left_n2 = check_node(root.left, n2) 
    
    #if n1 is on the left and n2 is not on the left, that means n2 is on the right
    #therefore the current root is the lowest common ancestor
    
    if check_left_n1!=check_left_n2:
        return root.data
    
    #Otherwise there is a lower common ancestor further down either the right or the left
    print (check_left_n1, check_left_n2, root.data)
    #If both n1 and n2 are on the left, then search left
    if check_left_n1==check_left_n2==True:
        result = best_ancestor(root.left, n1, n2)
    else:
        result = best_ancestor(root.right, n1, n2)        
    
    return result

In [1262]:
best_ancestor(root, 9, 13)

True True 3
True True 4
False False 7


9

In [1162]:
#Sample tree
root = Node(3) 
root.left = Node(4) 
root.right = Node(5) 
root.left.left = Node(7) 
root.left.left.left = Node(-1)
root.left.left.right = Node(9)
root.left.left.right.left = Node(12)
root.left.left.right.right = Node(13)

In [1218]:
#you can't terminate the recursion early, but you can return the result


In [1219]:
check_node(root, -1)

3
4
7
-1
9
12
13
5


True

In [31]:
#Found every path in a binary tree
root = Node(2)
root.left = Node(3)
root.left.left = Node(4)
root.left.left.left = Node(-3)
root.left.right = Node(-1)
root.left.right.left = Node(5)
root.left.right.left.left = Node(7)
root.right = Node(4)
root.right.left = Node(-1)
root.right.left.left = Node(1)
root.right.right = Node(0)

In [32]:
 
# Helper function to print path from root  
# to leaf in binary tree 
def printPathsRec(root, path, pathLen): 
      
    # Base condition - if binary tree is 
    # empty return 
    if root is None: 
        return
  
    # add current root's data into  
    # path_ar list 
    print ('current root', root.data)
    # if length of list is gre 
    if(len(path) > pathLen):  
        print ('before here1', path, pathLen)
        path[pathLen] = root.data 
        print ('after here1', path, pathLen)
    else: 
        print ('before here2', path, pathLen)
        path.append(root.data) 
        print ('after here2', path, pathLen)
  
    # increment pathLen by 1 
    pathLen = pathLen + 1
    print ('path length after:' , pathLen)
    if root.left is None and root.right is None: 
          
        # leaf node then print the list 
        printArray(path, pathLen) 
    else: 
        # try for left and right subtree 
        printPathsRec(root.left, path, pathLen) 
        printPathsRec(root.right, path, pathLen) 
    print ('end of code', path, pathLen)
# Helper function to print list in which  
# root-to-leaf path is stored 
def printArray(ints, len): 
    for i in ints[0 : len]: 
        print(i," ",end="") 
    print() 

In [33]:
printPathsRec(root, [], 0) 

current root 2
before here2 [] 0
after here2 [2] 0
path length after: 1
current root 3
before here2 [2] 1
after here2 [2, 3] 1
path length after: 2
current root 4
before here2 [2, 3] 2
after here2 [2, 3, 4] 2
path length after: 3
current root -3
before here2 [2, 3, 4] 3
after here2 [2, 3, 4, -3] 3
path length after: 4
2  3  4  -3  
end of code [2, 3, 4, -3] 4
end of code [2, 3, 4, -3] 3
current root -1
before here1 [2, 3, 4, -3] 2
after here1 [2, 3, -1, -3] 2
path length after: 3
current root 5
before here1 [2, 3, -1, -3] 3
after here1 [2, 3, -1, 5] 3
path length after: 4
current root 7
before here2 [2, 3, -1, 5] 4
after here2 [2, 3, -1, 5, 7] 4
path length after: 5
2  3  -1  5  7  
end of code [2, 3, -1, 5, 7] 5
end of code [2, 3, -1, 5, 7] 4
end of code [2, 3, -1, 5, 7] 3
end of code [2, 3, -1, 5, 7] 2
current root 4
before here1 [2, 3, -1, 5, 7] 1
after here1 [2, 4, -1, 5, 7] 1
path length after: 2
current root -1
before here1 [2, 4, -1, 5, 7] 2
after here1 [2, 4, -1, 5, 7] 2
path l

In [ ]:
#print all k sum paths in a binary tree, descending only

In [35]:
def printVector(v, i):  
    for j in range(i, len(v)): 
        print(v[j], end = " ") 
    print() 

# A wrapper over printKPathUtil()  
def printKPath(root, k): 
  
    path =[] 
    printKPathUtil(root, path, k)  

In [43]:
# This function prints all paths  
# that have sum k  
def printKPathUtil(root, path, k):  
  
    # empty node  
    if (not root) : 
        return
    print ('root:',root.data)
    # add current node to the path  
    path.append(root.data)  
   
    # check if there's any k sum path  
    # in the left sub-tree.  
    printKPathUtil(root.left, path, k)  
  
    # check if there's any k sum path  
    # in the right sub-tree.  
    printKPathUtil(root.right, path, k)  
    print (path, 'root:',root.data)

    # check if there's any k sum path that  
    # terminates at this node  
    # Traverse the entire path as  
    # there can be negative elements too  
    f = 0
    for j in range(len(path) - 1, -1, -1):      
        f += path[j]  
  
        # If path sum is k, print the path  
        if (f == k) : 
            printVector(path, j)  
      
    # Remove the current element  
    # from the path  
    path.pop(-1)    

In [44]:
root = Node(1)  
root.left = Node(3)  
root.left.left = Node(2)  
root.left.right = Node(1)  
root.left.right.left = Node(1)  
root.right = Node(-1)  
root.right.left = Node(4)  
root.right.left.left = Node(1)  
root.right.left.right = Node(2)  
root.right.right = Node(5)  
root.right.right.right = Node(2)  

In [45]:
k = 5
printKPath(root, k) 

root: 1
root: 3
root: 2
[1, 3, 2] root: 2
3 2 
root: 1
root: 1
[1, 3, 1, 1] root: 1
3 1 1 
[1, 3, 1] root: 1
1 3 1 
[1, 3] root: 3
root: -1
root: 4
root: 1
[1, -1, 4, 1] root: 1
4 1 
1 -1 4 1 
root: 2
[1, -1, 4, 2] root: 2
-1 4 2 
[1, -1, 4] root: 4
root: 5
root: 2
[1, -1, 5, 2] root: 2
[1, -1, 5] root: 5
5 
1 -1 5 
[1, -1] root: -1
[1] root: 1


In [47]:
q = {(2,3 ):1, ('a', 'b'):10}

In [48]:
q[(2,3)]

1

In [50]:
'''
List the power set of set S 
'''

'\nList the power set of set S \n'

In [144]:
s=set(['a', 'b', 'c', 'd'])

In [163]:
q = set(['a', ('a', 'b')])

In [164]:
#mechanics of sets doesn't let you do this nicely
#maybe just do it with lists?

{'a', ('a', 'b')}

In [182]:
s.remove

['b', 'c']

In [227]:
def power_set(s, p_set):
    
    if len(s)==1:
        ele = s.pop()
        if len(ele)==1: return p_set | set([ele])
    
    for element in s:
        
        subset = set([tuple(s - set([element]))])
        
        p_set = p_set | power_set(subset, p_set)
    
    p_set = p_set | s
    #print(p_set)
    return p_set

In [250]:
def powset3(seq):
    print ('seq', seq)
    if seq:
        print ('if seq', seq)
        p = powset3(seq[1:])
        print ('p', p, seq, seq[:1])
        t = p + [x + seq[:1] for x in p]
        print ('t', t, seq)
        return t
    else:
        print ('else', seq)
        return [[]]

In [256]:
powset3([1, 2])

seq [1, 2]
if seq [1, 2]
seq [2]
if seq [2]
seq []
else []
p [[]] [2] [2]
t [[], [2]] [2]
p [[], [2]] [1, 2] [1]
t [[], [2], [1], [2, 1]] [1, 2]


[[], [2], [1], [2, 1]]

In [259]:
'''
tower of hanoi
'''

'\ntower of hanoi\n'

In [260]:
A = [3, 2, 1]
B = []
C = []

def move(n, source, target, auxiliary):
    if n > 0:
        # Move n - 1 disks from source to auxiliary, so they are out of the way
        move(n - 1, source, auxiliary, target)

        # Move the nth disk from source to target
        target.append(source.pop())

        # Display our progress
        print(A, B, C, '##############', sep='\n')

        # Move the n - 1 disks that we left on auxiliary onto target
        move(n - 1, auxiliary, target, source)

In [263]:
TowerOfHanoi(3, 'A', 'B', 'C')

Move disk 1 from source A to destination B
Move disk 2 from source A to destination C
Move disk 1 from source B to destination C
Move disk 3 from source A to destination B
Move disk 1 from source C to destination A
Move disk 2 from source C to destination B
Move disk 1 from source A to destination B


In [264]:
'''
Given n, print all valid parenthesis combinations

example,
n=3, return: ()()(), ((())), ()(()), (())(), (()())
'''

'\nGiven n, print all valid parenthesis combinations\n\nexample,\nn=3, return: ()()(), ((())), ()(()), (())(), (()())\n'

In [291]:
#This way will fail to get '{{}}{{}}' when n=4
#We must account for the left and right parenthesis separately
def parenthesis(n):
    
    if n==0: return []
    
    if n==1: return ['{}']
    
    prior = parenthesis(n-1)
    
    left = ['{}' + i for i in prior]
    
    right = [i+'{}' for i in prior]

    center = ['{' + i + '}' for i in prior]

    return list(set(left+right+center))

In [ ]:
#This is correct

def printParenthesis(str, n): 
    if(n > 0): 
        _printParenthesis(str, 0,  
                          n, 0, 0); 
    return; 
  
def _printParenthesis(str, pos, n,  
                      open, close): 
      
    if(close == n): 
        for i in str: 
            print(i, end = ""); 
        print(); 
        return; 
    else: 
        if(open > close): 
            str[pos] = '}'; 
            _printParenthesis(str, pos + 1, n,  
                              open, close + 1); 
        if(open < n): 
            str[pos] = '{'; 
            _printParenthesis(str, pos + 1, n,  
                              open + 1, close); 

In [ ]:
'''
Anagrams

Sort a list of strings such that anagrams are adjacent.
'''

In [2]:
import string

In [5]:
all_dict = {char:idx for idx, char in enumerate(string.ascii_lowercase)}

In [7]:
str_list = ['abcs', 'sdsa', 'absc', 'scba', 'qweqweqa', 'sdfsdfdsf', 'pop', 'ewqewqaq', 'oop', 'ppo']

In [11]:
freq_list=[]
for c_str in str_list:
    current_freq = [0 for i in range(26)]
    for char in c_str:
        current_freq[all_dict[char]]+=1
    freq_list.append(''.join([str(i) for i in current_freq]))

In [14]:
sorted(zip(str_list, freq_list), key=lambda x: x[1])

[('pop', '00000000000000120000000000'),
 ('ppo', '00000000000000120000000000'),
 ('oop', '00000000000000210000000000'),
 ('sdfsdfdsf', '00030300000000000030000000'),
 ('qweqweqa', '10002000000000003000002000'),
 ('ewqewqaq', '10002000000000003000002000'),
 ('sdsa', '10010000000000000020000000'),
 ('abcs', '11100000000000000010000000'),
 ('absc', '11100000000000000010000000'),
 ('scba', '11100000000000000010000000')]

In [25]:
def getbit(num, i):
    return ((num& (1<<i))!=0)


In [27]:
getbit(3, 3)

False

In [ ]:
#Enumerate all possible boards of length k, with two possible types of boards (long:l and short:s)

In [43]:
lengths = []

In [44]:
d_l = {'l':2, 's':1}

In [45]:
def plank(k, board):
    
    if len(board)==k:       
        
        final_board = ''.join(board)
        lengths.append(sum([d_l[i] for i in board]))
        print('board', final_board)
        
        return board
    
    for b_type in ['l', 's']:
        board.append(b_type)
        plank(k, board)
        board.pop()

In [46]:
plank(3, [])

board lll
board lls
board lsl
board lss
board sll
board sls
board ssl
board sss


In [48]:
set(lengths)

{3, 4, 5, 6}

In [100]:
seq = [2, -8, 3, -2, 4, 10]

In [101]:
l=1
r=len(seq)
count=0
best_sum = sum(seq)
best_l=l
best_r = r

In [102]:
l, r, best_sum

(1, 6, 9)

In [103]:
while l<r:
    
    current_sum = sum(seq[l:r])
    print (current_sum, best_sum, count, l, r)
    if current_sum>best_sum:
        best_sum=current_sum
        best_l=l
        best_r=r
        print ('test', best_sum, best_l, best_r)
    if count%2==0:
        l+=1
    else:
        r-=1
    count+=1

7 9 0 1 6
15 9 1 2 6
test 15 2 6
5 15 2 2 5
2 15 3 3 5
-2 15 4 3 4


In [104]:
best_l, best_r, best_sum

(2, 6, 15)

In [105]:
seq[best_l: best_r]

[3, -2, 4, 10]

In [171]:
'''
Water is denoted by 0, and land by none zero values, count the size of each enclosed body of water
or how many enclosed bodies there are
input = [[0, 2, 1, 0],
[0, 1, 0, 1],
[1, 1, 0, 0],
[0, 1, 0, 1]]


'''

array([[0, 2, 1, 0],
       [0, 1, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 0, 1]])

In [172]:
def check(i, j, seen):    
    
    if i<0 or i>A.shape[0]-1 or j<0 or j>A.shape[1]-1:
        return None
    
    if A[i][j]!=0:
        return None
    
    if (i, j) in seen:
        return None    
    
    seen[(i,j)]=1
    
    check(i+1, j, seen)
    check(i-1, j, seen)
    
    check(i+1, j+1, seen)    
    check(i-1, j-1, seen)    
    
    check(i, j-1, seen)
    check(i, j+1, seen)        
    
    check(i+1, j-1, seen)
    check(i-1, j+1, seen)

    return seen

In [173]:
seen={}
ponds = []
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if A[i][j]==0 and True not in [(i, j) in pond for pond in ponds]:
            current_pond = check(i, j, seen)
            
            seen = {}
            ponds.append(current_pond)

In [ ]:
'''
Largest subarray with equal number of letters and numbers
'''

In [36]:
a = [1,0,2,'e','f','g',1,0,'e',0,0,0,'e',0,'a']

In [97]:
def subarray(a):
    
    total_l = sum([1 for i in a if type(i)==str])
    total_n = len(a)-total_l
    
    l=total_l
    n = total_n

    for e in reversed(range(2, len(a), 1)):

        for b in range(0, e, 1):

            if n==l:
                return [b, e]
            
            if type(a[b])==str:
                l-=1
            else:
                n-=1
        
        if type(a[e])==str:
            total_l-=1
        else:
            total_n-=1
        l=total_l
        n=total_n

In [98]:
a=['a','a','a','a',1,1,'a',1,1,'a','a',1,'a','a',1,'a','a','a','a', 'a']

In [99]:
low, high = subarray(a)

In [101]:
a[low:high+1]

[1, 1, 'a', 1, 1, 'a', 'a', 1, 'a', 'a', 1, 'a']

In [ ]:
'''
Given a table of names and frequencies
and a table of synonyms, group them into true frequencies by the synonyms
'''

In [124]:
freqs = [['John',15], ['Jon',12], ['Chris',13], ['Kris',4], ['Christopher',19]]

In [125]:
syns = [['John', 'Jon'], ['John', 'Johnny'], ['Chris', 'Kris'], ['Chris', 'Christopher']]

In [128]:
#At most all synonyms are independent
#syn_buckets =[set([]) for i in range(len(syns))]
syn_buckets=[]

In [129]:
bucket=0
for idx, syn in enumerate(syns):
    if idx==0:
        syn_buckets.append(set(syn))
    else:
        if len(set(syn) & syn_buckets[bucket])!=0:
            syn_buckets[bucket] = syn_buckets[bucket] | set(syn)
        else:
            bucket+=1
            syn_buckets.append(set(syn))

In [130]:
syn_buckets

[{'John', 'Johnny', 'Jon'}, {'Chris', 'Christopher', 'Kris'}]

In [117]:
syn_buckets = [list(i) for i in syn_buckets if len(i)!=0]

In [113]:
dict_freqs = {name:freq for name,freq in freqs}

In [122]:
true_freq = [[syns, sum([dict_freqs[syn] for syn in syns if syn in dict_freqs.keys()])] for syns in syn_buckets]

In [162]:
'''
Long subsequence in one variable

Find the longest subsequence of elements in a list

a = [3, 10, 2, 1, 20]

output: [3, 10, 20]
'''

'\nLong subsequence in one variable\n\nFind the longest subsequence of elements in a list\n\na = [3, 10, 2, 1, 20]\n\noutput: [3, 10, 20]\n'

In [185]:
import copy

In [186]:
copy.deepcopy

<function copy.deepcopy>

In [291]:
a = [3, 10, 2, 1, 5, 20]
a = [10, 22, 9, 33, 21, 50, 41, 60, 80]
a = [3, 2]
a = [50, 3, 10, 7, 40, 80]
a = [50, 3, 40, 7, 10, 80]

dict_s = {}

def lis(a):
    
    #Base case, the longest subsequence of a list of size 1 is itself
    if len(a)==1:        
        dict_s[a[0]] = a
        return None
    if len(a)<1:        
        return None
    #Enumerate through possible longest sequences starting at index position 0 and ending at index position len(a)
    for i in range(len(a)):
        subseq = a[i:-1]
        
        if len(subseq)!=0:
            lis(subseq)            

            if dict_s[a[i]][-1]<a[-1]:
                dict_s[a[i]].append(a[-1])   
                
    dict_s[a[-1]] = [a[-1]]

In [292]:
lis(a)

In [293]:
dict_s, #solutions are not unique, there is a second solution [3, 7, 40, 80]

({3: [3, 40, 80],
  7: [7, 10, 80],
  10: [10, 80],
  40: [40, 80],
  50: [50, 80],
  80: [80]},)

In [300]:
#Let's try to do this without recursion at all
#Can't be done this simply doesn't work, as you need to check all positions
a = [3, 10, 2, 1, 5, 20]
a = [10, 22, 9, 33, 21, 50, 41, 60, 80]
a = [3, 2]
a = [50, 3, 10, 7, 40, 80]
a = [50, 3, 40, 7, 10, 80]
def lis(arr):
    n = len(arr)

    # Declare the list (array) for LIS and initialize LIS
    # values for all indexes
    lis = [1]*n

    prev = [0]*n
    for i in range(0, n):
        prev[i] = i

    # Compute optimized LIS values in bottom up manner
    for i in range (1 , n):
        for j in range(0 , i):
            if arr[i] > arr[j] and lis[i]< lis[j] + 1:
                lis[i] = lis[j]+1
                prev[i] = j
    print (prev)
    # Initialize maximum to 0 to get the maximum of all
    # LIS
    maximum = 0
    idx = 0

    # Pick maximum of all LIS values
    for i in range(n):
        if maximum < lis[i]:
            maximum = lis[i]
            idx = i

    seq = [arr[idx]]
    while idx != prev[idx]:
        idx = prev[idx]
        seq.append(arr[idx])

    return (maximum, reversed(seq))

In [301]:
max_lis, list_lis = lis(a)

[0, 1, 1, 1, 3, 4]


In [299]:
[i for i in list_lis]

[3, 7, 10, 80]

In [131]:
#Longest subsequence in two variables

In [156]:
input = np.array([(150, 10), (160, 160), (50, 150), (56, 90), (60, 95), (65, 100), (32, 100), (75, 110)])

In [157]:
sort_args = np.argsort(input, axis=0)

In [158]:
sorted_input_0 = input[sort_args[:,0]]
sorted_input_1 = input[sort_args[:,1]]

In [159]:
matched_seq = sorted_input_0 ==  sorted_input_1

In [160]:
list_continuous_subseq=[]
for i in range(len(matched_seq)):
    subseqs = []
    if matched_seq[i][0]==matched_seq[i][1]==True:
        for j in range(len(matched_seq[i:])):
            if False in matched_seq[i+j]: break
            subseqs.append(sorted_input_0[i+j])
    list_continuous_subseq.append(subseqs)

In [161]:
list_continuous_subseq

[[], [], [], [], [], [array([ 75, 110])], [], [array([160, 160])]]

In [303]:
'''
Largest contiguous sum
a = [2, -8, 3, -2, 4, -10]
returns [3, -2, 4]
'''

'\nLargest contiguous sum\na = [2, -8, 3, -2, 4, -10]\nreturns [3, -2, 4]\n'

In [ ]:
#Why is the trivial soln wrong?

In [304]:
a = [2, -8, 3, -2, 4, -10]

In [305]:
best_sum=0
best_seq=[]

for seq_length in range(1, len(a), 1):
    for idx in range(len(a)):
        if sum(a[idx:idx+seq_length])>best_sum:
            best_sum=sum(a[idx:idx+seq_length])
            best_seq = a[idx:idx+seq_length]

In [306]:
best_seq

[3, -2, 4]

In [307]:
'''
Majority element

Find the majority element in o(n) time and o(1) time
'''

'\nMajority element\n\nFind the majority element in o(n) time and o(1) time\n'

In [327]:
input = [1, 2, 5, 9, 5, 9, 5, 5, 5, 2, 2, 2, 2]

In [328]:
count = 0
m=0
for x in input:
    print('x:%d, m:%d, count:%d' % (x, m, count))
    if count==0:
        m=x
        count=1
    elif m==x:
        count+=1
    else:
        count-=1

x:1, m:0, count:0
x:2, m:1, count:1
x:5, m:1, count:0
x:9, m:5, count:1
x:5, m:5, count:0
x:9, m:5, count:1
x:5, m:5, count:0
x:5, m:5, count:1
x:5, m:5, count:2
x:2, m:5, count:3
x:2, m:5, count:2
x:2, m:5, count:1
x:2, m:5, count:0


In [397]:
'''
Largest Common subsequence

x0="ABCDGH"
x1="AEDFHR"

the LCS is "ADH"
'''

'\nLargest Common subsequence\n\nx0="ABCDGH"\nx1="AEDFHR"\n\nthe LCS is "ADH"\n'

In [506]:
x0="AGGTAB"
x1="GXTXAYB"

In [507]:
array = np.array([[0 for i in range(len(x0))] for i in range(len(x1))])
#Base case if x0="A"

In [508]:
for i in range(len(x0)):
    print (x1[0],x0[:i+1])
    if x1[0] in x0[:i+1]:
        array[0][i]=1

G A
G AG
G AGG
G AGGT
G AGGTA
G AGGTAB


In [510]:
for i in range(len(x1)):
    if x0[0] in x1[:i+1]:
        array[i][0]=1

In [512]:
for i in range(1, len(x1), 1):
    for j in range(1, len(x0), 1):
        #if i==3 and j==1:break
        print (i, j, x1[i], x0[:j+1], array[:i,j])
        if x1[i] in x0[:j+1]:
            array[i][j] = 1 + max(array[:i,j])
        else:
            array[i][j] = max(array[:i,j])
        print(array)

1 1 X AG [1]
[[0 1 1 1 1 1]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
1 2 X AGG [1]
[[0 1 1 1 1 1]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
1 3 X AGGT [1]
[[0 1 1 1 1 1]
 [0 1 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
1 4 X AGGTA [1]
[[0 1 1 1 1 1]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
1 5 X AGGTAB [1]
[[0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
2 1 T AG [1 1]
[[0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
2 2 T AGG [1 1]
[[0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
2 3 T AGGT [1 1]
[[0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 2 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
2 4 T AGGTA [1 1]
[[0 1 1 1 1

In [514]:
#Right idea wrong details
#Here is recursive version, the key is to look at it one character at a time instead of as substrings
def lcs(X, Y, m, n): 
  
    if m == 0 or n == 0: 
       return 0; 
    elif X[m-1] == Y[n-1]: 
       return 1 + lcs(X, Y, m-1, n-1); 
    else: 
       return max(lcs(X, Y, m, n-1), lcs(X, Y, m-1, n)); 

In [ ]:
#DP version from the bottom up
def lcs(X , Y): 
    # find the length of the strings 
    m = len(X) 
    n = len(Y) 
  
    # declaring the array for storing the dp values 
    L = [[None]*(n+1) for i in xrange(m+1)] 
  
    """Following steps build L[m+1][n+1] in bottom up fashion 
    Note: L[i][j] contains length of LCS of X[0..i-1] 
    and Y[0..j-1]"""
    for i in range(m+1): 
        for j in range(n+1): 
            if i == 0 or j == 0 : 
                L[i][j] = 0
            elif X[i-1] == Y[j-1]: 
                L[i][j] = L[i-1][j-1]+1
            else: 
                L[i][j] = max(L[i-1][j] , L[i][j-1]) 
  
    # L[m][n] contains the length of LCS of X[0..n-1] & Y[0..m-1] 
    return L[m][n] 
#end of function lcs 

In [2]:
'''
Return the k smallest numbers in an array
'''

'\nReturn the k smallest numbers in an array\n'

In [3]:
a = [random.randrange(-100, 100) for i in range(10)]

In [6]:
def k_small(k):
    
    k_smallest = []
    max_k_small=-999999
    max_k_arg = 0
    for i in range(len(a)):
        if len(k_smallest)<k:
            k_smallest.append(a[i])            
        else:
            max_id = np.argmax(k_smallest)
            if k_smallest[max_id]>a[i]:
                k_smallest[max_id]=a[i]
                
    return k_smallest

In [8]:
k_small(3)

[-49, -51, -37]

In [10]:
import heapq

In [16]:
a = [1,2,4,10,-1]

In [17]:
heapq.heapify(a)

In [18]:
a[0]

-1

In [74]:
'''
Max black squares
Given a square matrix find the largest subsquare that is all black
'''

'\nMax black squares\nGiven a square matrix find the largest subsquare that is all black\n'

In [68]:
A = np.array([[1,0,1,0,0,0,0],
              [1,1,0,0,0,0,1],
              [0,0,0,1,1,1,0],
              [0,0,1,1,1,1,0],
              [0,0,1,0,0,1,0],
              [0,0,1,0,0,1,0],
              [0,0,1,1,1,1,0]])

In [71]:
filled_squares = []
hollow_squares = []
for size in reversed(range(2, A.shape[0]+1, 1)):
#    print(size)    
    for x in range(0, A.shape[0]-size+1, 1):
        for y in range(0, A.shape[0]-size+1, 1):
            #print(x, y)
            if sum(sum(A[x:x+size,y:y+size]))==size*size:
                #print(A[x:x+size,y:y+size])
                filled_squares.append(size*size)
            if sum(A[x:x+size,y:y+size][0])==sum(A[x:x+size,y:y+size][-1])==sum(A[x:x+size,y:y+size][:,0])==sum(A[x:x+size,y:y+size][:,-1])==size:
                hollow_squares.append(A[x:x+size,y:y+size])

In [73]:
hollow_squares

[array([[1, 1, 1, 1],
        [1, 0, 0, 1],
        [1, 0, 0, 1],
        [1, 1, 1, 1]]), array([[1, 1],
        [1, 1]]), array([[1, 1],
        [1, 1]])]

In [ ]:
'''
max submatrix

Given a square matrix of postive and negative elements
find the submatrix with the largest sum
'''

In [75]:
n=6
A = np.array([[random.randrange(-10, 10) for i in range(n)] for j in range(n)])

In [129]:
max_sum = -float('inf')

max_id = [(-1, 1), (-1, -1)]

for w in range(1, A.shape[0]+1, 1): #<--- need to go up to A.shape[0]+1 because indexing is not inclusive on right side
    for h in range(1, A.shape[0]+1, 1):
        for i in range(0, A.shape[0]-w+1, 1):
            for j in range(0, A.shape[0]-h+1, 1):
                c_sum = sum(sum(A[i:i+w, j:j+h]))
                if c_sum>max_sum:
                    max_sum=c_sum
                    max_id = [(i,j), (i+w,j+h)]

In [130]:
max_sum

32

In [131]:
max_id

[(0, 3), (2, 6)]

In [170]:
dict_row_sums[(0, 6)], dict_row_sums[(1, 6)]

(3, -6)

In [171]:
dict_row_sums[(0, 3)], dict_row_sums[(1, 3)]

(-19, -16)

In [136]:
A

array([[-6, -5, -8,  7,  8,  7],
       [-1, -7, -8,  8,  8, -6],
       [-4, -2,  1, -7, -5,  8],
       [ 9, -9,  0, -7,  8, -4],
       [-6, -1, -6, -8, -1, -3],
       [ 8,  1,  0, -6, -5,  5]])

In [135]:
A[max_id[0][0]:max_id[1][0], max_id[0][1]:max_id[1][1]]

array([[ 7,  8,  7],
       [ 8,  8, -6]])

In [101]:
dict_row_sums={}

In [147]:
for i in range(0, A.shape[0], 1):
    for j in range(0, A.shape[0]+1, 1):
        dict_row_sums[(i, j)]  = sum(A[i,0:j])

In [206]:
A

array([[-6, -5, -8,  7,  8,  7],
       [-1, -7, -8,  8,  8, -6],
       [-4, -2,  1, -7, -5,  8],
       [ 9, -9,  0, -7,  8, -4],
       [-6, -1, -6, -8, -1, -3],
       [ 8,  1,  0, -6, -5,  5]])

In [205]:
dict_row_sums[(0, 1)]

-6

In [227]:
max_sum = -float('inf')

max_id = [(-1, 1), (-1, -1)]

for w in range(1, A.shape[0]+1, 1): #<--- need to go up to A.shape[0]+1 because indexing is not inclusive on right side    
    for h in range(1, A.shape[0]+1, 1):        
        for i in range(0, A.shape[0]-w+1, 1):            
            for j in range(0, A.shape[0]-h+1, 1):                             
                p_sum =0
                n_sum = 0
                for k in range(j, h, 1):     
                    p_sum+=dict_row_sums[(k, w+i)]
                    n_sum+=dict_row_sums[(k, i)]
                
                c_sum = p_sum-n_sum
                if c_sum>max_sum:
                    max_sum=c_sum
                    max_id = [(j,i), (j+h,i+w)]

In [230]:
#Even better w can iteratively construct the dictionary for the area 
#dict_submatrix = {(x,y):area}

In [277]:
#Store the area of all subarrays starting at 0,0 and ending at x,y
#This is in fact O(n^4) because you need to sum the array
dict_area_xy ={}
for x in range(0, A.shape[0]+1, 1):
    for y in range(0, A.shape[0]+1, 1):
        if x==0 or y==0:             
            dict_area_xy[(x,y)]=0
        else:
            dict_area_xy[(x,y)]=sum(sum(A[:x,:y]))

In [291]:
max_sum = -float('inf')

max_id = [(-1, 1), (-1, -1)]

for x0 in range(A.shape[0]):
    for y0 in range(A.shape[0]):        
        for x1 in range(x0+1, A.shape[0]+1, 1):
            for y1 in range(y0+1, A.shape[0]+1, 1):
                total_area = dict_area_xy[(x1, y1)]
                top_left_corner = dict_area_xy[(x0, y0)]
                top = dict_area_xy[(x1, y0)]
                bottom = dict_area_xy[(x0, y1)]
                c_sum = total_area-top-bottom+top_left_corner
                
                if c_sum>max_sum:
                    max_sum=c_sum
                    max_id = [(x0,y0), (x1,y1)]

In [ ]:
#Even faster using Kadane's algorithm to find the 1d largest subarray

In [347]:
max_sum = -float('inf')

max_id = [(-1, 1), (-1, -1)]

for x0 in range(A.shape[0]):
    #if x0!=3:continue
    for x1 in range(x0+1, A.shape[0]+1, 1):
        #if x1!=6:continue
        column_sum = []
        for idx in range(A.shape[0]):
            print(idx, col, x0, x1)            
            column_sum.append(sum(A[x0:x1,idx]))
        
        best_sum=-999999
        current_sum = best_sum
        best_start=best_end=0
        
        for idx, value in enumerate(column_sum):
            
            if idx==0:
                best_sum=value
                current_sum = value
            else:
                current_sum=+value
            
            if current_sum>best_sum:
                best_sum=current_sum
                best_end=idx+1
        
        #max_subseq = find_max_subseq(column_sum)
            
#                c_sum = total_area-top-bottom+top_left_corner
                
 #               if c_sum>max_sum:
 #                   max_sum=c_sum
  #                  max_id = [(x0,y0), (x1,y1)]

0 6 3 6
1 6 3 6
2 6 3 6
3 6 3 6
4 6 3 6
5 6 3 6


In [367]:
column_sum = [random.randrange(-10,10) for i in range(10)]

In [368]:
column_sum

[-3, 6, 8, 4, 4, -1, 2, -5, -5, -8]

In [377]:
best_sum=0
current_sum = 0
best_start=best_end=0
for current_end, value in enumerate(column_sum):
    
    if current_sum<=0:      
        current_start=current_end
        current_sum = value
    else:
        current_sum+=value
    print(current_end, value, current_sum)
    if current_sum>best_sum:
        best_sum=current_sum
        best_start=current_start
        best_end=current_end+1

0 -3 -3
1 6 6
2 8 14
3 4 18
4 4 22
5 -1 21
6 2 23
7 -5 18
8 -5 13
9 -8 5


In [ ]:
'''
Print the kth number such that its only prime factors are 3, 5, 7, it does not have to have all 
three prime factors but it must not have any other prime factors.

The first four k's are [1, 3, 5, 7]
'''

In [397]:
125*3

375

In [389]:
def kth_multiple(k):
    a = [1, 3, 5, 7]
    
    if k<4:
        return a[:k]
    
    else:
        idx_3=0
        idx_5=0
        idx_7=0
        while len(a)<k:
            
            while 3*a[idx_3] in a:
                idx_3+=1
                
            while 5*a[idx_5] in a:
                idx_5+=1
                
            while 7*a[idx_7] in a:
                idx_7+=1
                
            a.append(min(3*a[idx_3], 5*a[idx_5], 7*a[idx_7]))
            
        return a

In [398]:
#kth_multiple(100)

In [ ]:
dict_ab = {}#key is (a, b):value?
#you would have to cache the results up to this point so it can be repeatedly used everytime you execute the program

In [444]:
#Two factor version
def kth_multiple(k):
    values = [1, 3, 5]    
    if k<3:
        return values[:k]
    
    else:
        n = k-len(values)        
        for i in range(n):#<-- maybe I can cache these results?
        
            v_min=9999
            for a in range(0, k+1, 1):                
                pow_a = pow(3, a) #can save some compute here
                for b in range(0, k+1, 1):
                    if a+b>k:continue
                    
                    c_value = pow_a*pow(5, b)
                    #print(a, b, i, c_value)
                    if c_value<v_min and c_value>values[-1]:
                        v_min=c_value

            values.append(v_min)

        return values

In [448]:
kth_multiple(10)

[1, 3, 5, 9, 15, 25, 27, 45, 75, 81]

In [449]:
'''
Sort by custom alphabet
'''

"\nSort by custom alphabet\n\nalphabet = 'zkaioqwst'\n"

In [450]:
alphabet = 'zkaioqwst'

In [465]:
alphabet_dict = {value:idx for idx,value in enumerate(alphabet)}

In [473]:
list_str = []

for word in range(10):
    word_length = random.randrange(1, 10)
    word=[]
    for i in range(word_length):
        word.append(alphabet[random.randrange(0, len(alphabet))])
    list_str.append(''.join(word))

In [474]:
list_str

['awszsw', 'tstzza', 'aitkwwqa', 's', 'koz', 'zikkz', 's', 't', 'iok', 'so']

In [476]:
list_str+=['sk']

In [477]:
list_str

['awszsw',
 'tstzza',
 'aitkwwqa',
 's',
 'koz',
 'zikkz',
 's',
 't',
 'iok',
 'so',
 'sk']

In [478]:
sorted(list_str, key=lambda x:[alphabet_dict[i] for i in x])

['zikkz',
 'koz',
 'aitkwwqa',
 'awszsw',
 'iok',
 's',
 's',
 'sk',
 'so',
 't',
 'tstzza']

In [480]:
'''
Largest sum in increasing order, excluding adjacent values
a = [30, 15, 60, 75, 45, 15, 15, 45]
output=180
'''

'\nLargest sum in increasing order, excluding adjacent values\na = [30, 15, 60, 75, 45, 15, 15, 45]\noutput=180\n'

In [556]:
a = [30, 15, 60, 75, 45, 15, 15, 45]
#a=[75, 105, 120, 75, 90, 135]
#Starting from last value
def bs(a, k):
    
    if len(a)<1: return 0
    #print ('k:',k, 'a[-k]:', a[-1])
    if len(a)==1:return a[0]
    
    best_sum = max(a[-1]+bs(a[:k-2], k-2), bs(a[:k-1], k-1))
    
    return best_sum

In [557]:
bs(a, len(a)-1)

180

In [558]:
#Start from first value instead
def bs(k):
    if k>=len(a):
        return 0
    
    best_sum = max(a[k]+bs(k+2), bs(k+1))
    
    return best_sum

In [559]:
bs(0)

180

In [571]:
#Memoize to prevent recursive calls
dict_bs = {} #The key should be the kth value
def bs(k):
    if k>=len(a):
        return 0
    if k not in dict_bs.keys():
        best_with_k = a[k]+bs(k+2)
        best_without_k = bs(k+1)        
        dict_bs[k] = max(best_with_k, best_without_k)
    
    return dict_bs[k]

In [572]:
bs(0)

180

In [574]:
#Even better doing it in place, much harder to understand...
oneaway=0
twoaway=0
for i in reversed(range(len(a))):
    best_with = a[i]+twoaway
    best_without = oneaway
    
    best_current = max(best_with, best_without)
    
    twoaway=oneaway
    oneaway=best_current

In [575]:
oneaway, twoaway

(180, 150)

In [1]:
'''
respace

Insert spaces into a concatenated doc without spaces given a dictionary 
such that the least amount of chars are unk
'''

'\nrespace\n\nInsert spaces into a concatenated doc without spaces given a dictionary \nsuch that the least amount of chars are unk\n'

In [95]:
input[4:4+6]

'looked'

In [98]:
input[4+6:4+6+1]

'j'

In [122]:
input = 'jesslookedjustliketimherbrothertt'

words = set(['looked', 'just', 'like', 'her', 'brother', 'er'])

max_length = max([len(i) for i in dict_words])

spaced_input = []
unk_chars = []
idx=0
is_unk= True
while idx<len(input):
    
    for j in reversed(range(1, max_length+1+min(0, len(input)-max_length-idx), 1)):        
        #print (idx, j, input[idx:idx+j], max_length+1+min(0, len(input)-max_length-idx), len(input)-max_length-idx)
        if input[idx:idx+j] in words:
            spaced_input.append([input[idx:idx+j], [idx, idx+j]])
            idx=idx+j
            is_unk = False    
            break
    
    if is_unk is True:        
        unk_chars.append([input[idx], idx])
        idx+=1#<--- only increment if idx is not incremented by j
    if is_unk is False:
        is_unk=True
    

In [125]:
input[:2]

'je'

In [126]:
input[2:]

'sslookedjustliketimherbrothertt'

In [123]:
spaced_input

[['looked', [4, 10]],
 ['just', [10, 14]],
 ['like', [14, 18]],
 ['her', [21, 24]],
 ['brother', [24, 31]]]

In [124]:
unk_chars

[['j', 0],
 ['e', 1],
 ['s', 2],
 ['s', 3],
 ['t', 18],
 ['i', 19],
 ['m', 20],
 ['t', 31],
 ['t', 32]]

In [ ]:
#Whats the recursive way of doing this? I don't even understand why you want to do it recursively

In [166]:
def comb(x, k, combs):

    if k==len(x)-1:
        combs.append(''.join(x))
        return None
        
    for i in range(k, len(x), 1):
        x[i],x[k] = x[k],x[i]

        comb(x, k+1, combs)
        x[k],x[i] = x[i],x[k]
        
    return combs

In [167]:
q = comb(list('abcd'), 0, [])

In [169]:
len(q)

24